# Generated by Django 5.2.1 on 2025-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('category', models.CharField(max_length=100, verbose_name='الصنف')),
                ('brand', models.CharField(max_length=100, verbose_name='الصنف')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='السعر')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
    ]
